### ISSUE TITLE
Backbone collection is pulling an entire table when it should only be pulling some

### ISSUE THREAD

**Issue by adamgallinat** [adamgallinat/partner#2]
All of my 'method' objects are being stored in a single table, with a column denoting what technology they belong to.

I have a collection whose job it is to populate itself with JUST the methods associated with a specific technology. However, when I create that collection, it appears to be performing two different actions: filling itself with the methods I'm looking for, and then making a second request behind the scenes to add the rest of the methods from the methods table (regardless of what technology they belong to).

I'm afraid that whatever's happening here is a feature of Backbone that I don't understand. I've tried looking around on the internet for an explanation, but so far have come up short.

```
// Collection Constructor
App.Collections.Methods = Backbone.Collection.extend({
    initialize: function() {
        console.log('new methods collection created');
        this.fetch();
    },
    model: App.Models.Method,
    comparator: 'name',
    url: '/methods'
});

// Method being called
$.get('/methods/of_type/' + App.currentTechnology)
    .done(function(methods) {
App.methods = new App.Collections.Methods(methods);
});
```

@bigtone1284 @WilliamfShaw @h4w5

**Comment by bigtone1284** [comment]
taken

@WilliamfShaw  @h4w5
